version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: user-db
    environment:
      POSTGRES_DB: chatbotdb
      POSTGRES_USER: chatbotuser
      POSTGRES_PASSWORD: password123
      TZ: Asia/Kolkata
    ports:
      - "5432:5432"
    volumes:
      - user-data:/var/lib/postgresql/data

volumes:
  user-data: