version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: chatbot-postgres
    environment:
      POSTGRES_DB: chatbotdb
      POSTGRES_USER: chatbotuser
      POSTGRES_PASSWORD: password123
      TZ: Asia/Kolkata
    ports:
      - "5432:5432"
