server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chatbotdb
    username: chatbotuser
    password: chatbotpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: user-service
